"""empty message

Revision ID: 3e67710fab1e
Revises: 
Create Date: 2023-10-21 19:03:50.535770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e67710fab1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('category', sa.Enum('colchones', 'canapes', 'cabeceros', 'armarios', 'sofas', 'mesas', 'sillas', name='myenum'), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.Column('publishing_date', sa.String(length=10), nullable=False),
    sa.Column('image', sa.String(length=2000), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('profundidad', sa.Integer(), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.Column('grosor', sa.Integer(), nullable=True),
    sa.Column('firmeza', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('ancho', sa.Integer(), nullable=True),
    sa.Column('longitud', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=1000), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('surname', sa.String(length=40), nullable=False),
    sa.Column('image', sa.String(length=300), nullable=False),
    sa.Column('location', sa.String(length=40), nullable=False),
    sa.Column('carrito', sa.ARRAY(sa.String(length=400)), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('item')
    # ### end Alembic commands ###
