"""empty message

Revision ID: 4fe5cabc76a0
Revises: 50cc2bbff45e
Create Date: 2023-10-18 14:23:25.133990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4fe5cabc76a0'
down_revision = '50cc2bbff45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('firmeza')
        batch_op.drop_column('profundidad')
        batch_op.drop_column('description')
        batch_op.drop_column('location')
        batch_op.drop_column('price')
        batch_op.drop_column('altura')
        batch_op.drop_column('grosor')
        batch_op.drop_column('image')
        batch_op.drop_column('capacidad')
        batch_op.drop_column('publishing_date')
        batch_op.drop_column('counter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('counter', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('publishing_date', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('capacidad', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('grosor', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('altura', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('profundidad', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('firmeza', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type', postgresql.ENUM('colchones', 'canapes', 'cabeceros', 'sofas', 'armarios', name='myenum'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
