"""empty message

Revision ID: 5089f274e49f
Revises: 984c535206bc
Create Date: 2023-10-20 21:59:01.590801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5089f274e49f'
down_revision = '984c535206bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('carrito',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=120)),
               type_=sa.ARRAY(sa.String(length=400)),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('carrito',
               existing_type=sa.ARRAY(sa.String(length=400)),
               type_=postgresql.ARRAY(sa.VARCHAR(length=120)),
               existing_nullable=True)

    # ### end Alembic commands ###
