"""empty message

Revision ID: 5275b381cb1c
Revises: 91b3c981fce1
Create Date: 2023-10-18 14:30:08.896737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5275b381cb1c'
down_revision = '91b3c981fce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('profundidad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('capacidad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('altura', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grosor', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('firmeza', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('firmeza')
        batch_op.drop_column('grosor')
        batch_op.drop_column('altura')
        batch_op.drop_column('capacidad')
        batch_op.drop_column('profundidad')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
