"""empty message

Revision ID: 91b3c981fce1
Revises: f038bac9bdba
Create Date: 2023-10-18 14:29:20.262715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91b3c981fce1'
down_revision = 'f038bac9bdba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.ENUM('colchones', 'canapes', 'cabeceros', 'sofas', 'armarios', name='myenum'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
