"""empty message

Revision ID: a65f2acb7554
Revises: 5275b381cb1c
Create Date: 2023-10-18 14:35:36.392310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65f2acb7554'
down_revision = '5275b381cb1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('colchones', 'canapes', 'cabeceros', 'sofas', 'armarios', name='myenum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
