"""empty message

Revision ID: aacdadc798ea
Revises: 1f87c18a6a1c
Create Date: 2023-10-18 17:47:01.956606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aacdadc798ea'
down_revision = '1f87c18a6a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.ENUM('colchones', 'canapes', 'cabeceros', 'sofas', 'armarios', name='myenum'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
