"""empty message

Revision ID: f038bac9bdba
Revises: fdbd8104acfc
Create Date: 2023-10-18 14:25:54.297185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f038bac9bdba'
down_revision = 'fdbd8104acfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
