"""empty message

Revision ID: f450ef4d7a1b
Revises: a65f2acb7554
Create Date: 2023-10-18 15:14:37.063045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f450ef4d7a1b'
down_revision = 'a65f2acb7554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', postgresql.ENUM('colchones', 'canapes', 'cabeceros', 'sofas', 'armarios', name='myenum'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
