"""empty message

Revision ID: fdbd8104acfc
Revises: 4fe5cabc76a0
Create Date: 2023-10-18 14:25:11.795833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdbd8104acfc'
down_revision = '4fe5cabc76a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('colchones', 'canapes', 'cabeceros', 'sofas', 'armarios', name='myenum'), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=1000), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('publishing_date', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('image', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('counter', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('counter')
        batch_op.drop_column('image')
        batch_op.drop_column('publishing_date')
        batch_op.drop_column('location')
        batch_op.drop_column('description')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
